# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            지극히 개인적인 블로그
tagline:          'For Data Science & SW Engineering'
description:
url:              https://slykid.github.io
baseurl:          /

author:
  name:           'Kilhyun Kim'
  url:            https://www.instagram.com/slyk1d.93/?hl=ko

paginate:         

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/slykid/slykid.github.io.git
